"""Markdown report generation for CultureTrust AI."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any


def render_markdown_report(
    evaluation: dict[str, Any],
    model_name: str,
    model_version: str | None = None,
) -> str:
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    version_text = f" ({model_version})" if model_version else ""

    lines = [
        "# CultureTrust AI Evaluation Report",
        "",
        f"Model: {model_name}{version_text}",
        f"Generated: {generated_at}",
        "",
        "## Summary",
        "",
        f"- Overall Trust Score: {evaluation['overall_score']} / 100",
        f"- Risk Level: {evaluation['risk_level']}",
        f"- Cases Evaluated: {evaluation['case_count']}",
        "",
        "## Case Results",
        "",
    ]

    for result in evaluation["results"]:
        lines.extend(render_case_result(result))

    if evaluation["missing_cases"]:
        lines.extend([
            "## Missing Cases",
            "",
            "Responses referenced case IDs that were not found in the case file:",
            "",
        ])
        lines.extend(f"- {case_id}" for case_id in evaluation["missing_cases"])
        lines.append("")

    lines.extend([
        "## Disclaimer",
        "",
        "This report is generated by an evaluation toolkit. It is not legal advice, regulatory approval, or official certification.",
        "",
    ])

    return "\n".join(lines)


def render_case_result(result: dict[str, Any]) -> list[str]:
    lines = [
        f"### {result['title']}",
        "",
        f"- Case ID: `{result['case_id']}`",
        f"- Locale: {result['locale']}",
        f"- Language: {result['language']}",
        f"- Domain: {result['domain']}",
        f"- Overall Score: {result['overall_score']} / 100",
        f"- Risk Level: {result['risk_level']}",
        f"- Strongest Dimension: {result['strongest_dimension']}",
        f"- Weakest Dimension: {result['weakest_dimension']}",
        f"- Recommendation: {result['recommendation']}",
        "",
        "| Dimension | Score | Weight |",
        "|---|---:|---:|",
    ]

    for dimension in result["dimension_scores"]:
        weight = int(dimension["weight"] * 100)
        lines.append(f"| {dimension['label']} | {dimension['score']} / 100 | {weight}% |")

    lines.extend(["", "Reviewer Notes:", ""])
    for dimension in result["dimension_scores"]:
        note = dimension["notes"][0] if dimension["notes"] else "No notes."
        lines.append(f"- {dimension['label']}: {note}")

    lines.append("")
    return lines
